import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./nav/Navbar";



export const metadata: Metadata = {
  title: "My Auction App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body>
        <Navbar />
      </body>

      <main className="container mx-auto px-5 pt-10">
        {children}
      </main>
      
    </html>
  );
}
